name: draggable_animation
description: >
  A Flutter package that enables smooth drag-and-drop animations between menu areas, 
  inspired by iOS-style rearranging. Perfect for custom animated menus and item sorting.

version: 0.0.2
homepage : https://horleng.vercel.app/
repository: https://github.com/horlengg/flutter_draggable_animation

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
